"""Generalize_Embedding_for_docs_and_entities

Revision ID: 137fd936b41e
Revises: fb64534ff5fb
Create Date: 2024-04-30 11:06:06.017084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '137fd936b41e'
down_revision: Union[str, None] = 'fb64534ff5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('document_embeddings')
    op.add_column('document', sa.Column('embedding_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'embeddings', ['embedding_id'], ['id'])
    op.add_column('entity', sa.Column('embedding_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entity', 'embeddings', ['embedding_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.drop_column('entity', 'embedding_id')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'embedding_id')
    op.create_table('document_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embeddings', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='document_embeddings_pkey')
    )
    op.drop_table('embeddings')
    # ### end Alembic commands ###
