"""Adding metadata fields to Document

Revision ID: 30b3b5fb0d3e
Revises: a05e58314a8f
Create Date: 2024-05-20 12:54:07.732447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30b3b5fb0d3e'
down_revision: Union[str, None] = 'a05e58314a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('metadata_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('metadata_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('site_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('document', 'authors',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('testlist', 'text3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testlist', sa.Column('text3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('document', 'authors',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.drop_column('document', 'site_name')
    op.drop_column('document', 'image_url')
    op.drop_column('document', 'locale')
    op.drop_column('document', 'metadata_description')
    op.drop_column('document', 'metadata_keywords')
    # ### end Alembic commands ###
