"""Add update_at to Embedding

Revision ID: 33d00ba2fc7d
Revises: 5f062f4c8e3f
Create Date: 2024-05-23 09:54:08.928542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '33d00ba2fc7d'
down_revision: Union[str, None] = '5f062f4c8e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding', 'update_at')
    # ### end Alembic commands ###
