"""Remove test fields

Revision ID: 343692566f42
Revises: 230e7fda18b5
Create Date: 2024-05-06 20:04:09.724087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '343692566f42'
down_revision: Union[str, None] = '230e7fda18b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('descriptions', sa.JSON(), nullable=True))
    op.drop_column('entity', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('entity', 'descriptions')
    # ### end Alembic commands ###
