"""Fix relationship typos

Revision ID: 39339a4d74db
Revises: 137fd936b41e
Create Date: 2024-04-30 11:10:36.533452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '39339a4d74db'
down_revision: Union[str, None] = '137fd936b41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
