"""This is fixing documnet typo

Revision ID: 3c4e27bee9eb
Revises: 7ba5071e5476
Create Date: 2024-05-02 14:47:49.192975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '3c4e27bee9eb'
down_revision: Union[str, None] = '7ba5071e5476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopic_document_link', sa.Column('document_id', sa.Integer(), nullable=False))
    op.drop_constraint('subtopic_document_link_documnet_id_fkey', 'subtopic_document_link', type_='foreignkey')
    op.create_foreign_key(None, 'subtopic_document_link', 'document', ['document_id'], ['id'])
    op.drop_column('subtopic_document_link', 'documnet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopic_document_link', sa.Column('documnet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subtopic_document_link', type_='foreignkey')
    op.create_foreign_key('subtopic_document_link_documnet_id_fkey', 'subtopic_document_link', 'document', ['documnet_id'], ['id'])
    op.drop_column('subtopic_document_link', 'document_id')
    # ### end Alembic commands ###
