"""Test list

Revision ID: 58c59ef2248e
Revises: 343692566f42
Create Date: 2024-05-07 08:04:46.332258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58c59ef2248e'
down_revision: Union[str, None] = '343692566f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('texts2', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('json1', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testlist')
    # ### end Alembic commands ###
