"""Adding notes to subtopic_embedding_link

Revision ID: 5f062f4c8e3f
Revises: 30b3b5fb0d3e
Create Date: 2024-05-23 09:07:05.036905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '5f062f4c8e3f'
down_revision: Union[str, None] = '30b3b5fb0d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopic_embedding_link', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtopic_embedding_link', 'notes')
    # ### end Alembic commands ###
