"""Rename Embedding model

Revision ID: 642395b8abdd
Revises: 84c3bdb1f2c8
Create Date: 2024-05-01 08:21:18.867052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '642395b8abdd'
down_revision: Union[str, None] = '84c3bdb1f2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey')
    )
    op.drop_table('embedding')
    # ### end Alembic commands ###
