"""Remove relationships between Entity Document and Embedding

Revision ID: 84c3bdb1f2c8
Revises: 3491144dde68
Create Date: 2024-05-01 08:19:35.523896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '84c3bdb1f2c8'
down_revision: Union[str, None] = '3491144dde68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_embedding_id_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'embedding_id')
    op.add_column('embeddings', sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('embeddings', sa.Column('source_id', sa.Integer(), nullable=False))
    op.drop_constraint('entity_embedding_id_fkey', 'entity', type_='foreignkey')
    op.drop_column('entity', 'embedding_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('embedding_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('entity_embedding_id_fkey', 'entity', 'embeddings', ['embedding_id'], ['id'])
    op.drop_column('embeddings', 'source_id')
    op.drop_column('embeddings', 'source_type')
    op.add_column('document', sa.Column('embedding_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_embedding_id_fkey', 'document', 'embeddings', ['embedding_id'], ['id'])
    # ### end Alembic commands ###
