"""Embedding Subtopic Rel

Revision ID: 85d485a3b105
Revises: 5011695d655e
Create Date: 2024-05-01 14:54:59.269808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '85d485a3b105'
down_revision: Union[str, None] = '5011695d655e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtopic_embedding_link',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_id'], ['embedding.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], ),
    sa.PrimaryKeyConstraint('subtopic_id', 'embedding_id')
    )
    op.drop_table('subtopic_entity_link')
    op.add_column('subtopic', sa.Column('vector', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    op.drop_column('subtopic', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopic', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True))
    op.drop_column('subtopic', 'vector')
    op.create_table('subtopic_entity_link',
    sa.Column('subtopic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name='subtopic_entity_link_entity_id_fkey'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], name='subtopic_entity_link_subtopic_id_fkey'),
    sa.PrimaryKeyConstraint('subtopic_id', 'entity_id', name='subtopic_entity_link_pkey')
    )
    op.drop_table('subtopic_embedding_link')
    # ### end Alembic commands ###
