"""Add version to Entity and Embedding

Revision ID: a05e58314a8f
Revises: ee6b65a35e02
Create Date: 2024-05-07 15:05:43.239772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a05e58314a8f'
down_revision: Union[str, None] = 'ee6b65a35e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('entity', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'version')
    op.drop_column('embedding', 'version')
    # ### end Alembic commands ###
