"""Enitit Document Subtopic Rel

Revision ID: a6bf5f1e3824
Revises: 85d485a3b105
Create Date: 2024-05-02 10:23:53.514575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a6bf5f1e3824'
down_revision: Union[str, None] = '85d485a3b105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtopic_document_link',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('documnet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documnet_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], ),
    sa.PrimaryKeyConstraint('subtopic_id', 'documnet_id')
    )
    op.create_table('subtopic_entity_link',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], ),
    sa.PrimaryKeyConstraint('subtopic_id', 'entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopic_entity_link')
    op.drop_table('subtopic_document_link')
    # ### end Alembic commands ###
