"""add text3 to TestList

Revision ID: ee6b65a35e02
Revises: 4fda6bb3a0f9
Create Date: 2024-05-07 11:35:30.203873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ee6b65a35e02'
down_revision: Union[str, None] = '4fda6bb3a0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('descriptions_bank', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('testlist', sa.Column('text3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testlist', 'text3')
    op.drop_column('entity', 'descriptions_bank')
    # ### end Alembic commands ###
