"""Docs_Entities_Link

Revision ID: fb64534ff5fb
Revises: 3b0ed01afc25
Create Date: 2024-04-30 08:49:06.437692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'fb64534ff5fb'
down_revision: Union[str, None] = '3b0ed01afc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_entity_link',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'entity_id')
    )
    op.drop_constraint('entity_document_id_fkey', 'entity', type_='foreignkey')
    op.drop_column('entity', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('entity_document_id_fkey', 'entity', 'document', ['document_id'], ['id'])
    op.drop_table('document_entity_link')
    # ### end Alembic commands ###
