# docker-compose.yml

version: '3.8'

services:
  api:
    container_name: icog-api
    build: .
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port "8889"
    environment:
      PORT: 8889
    volumes:
      - .:/app
    ports:
      - 8889:8889
    restart: "no"