"""Adding Entity relationship to subtopic

Revision ID: 0318c32e01dc
Revises: fa4b2a7ee66d
Create Date: 2024-04-12 12:11:52.508906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '0318c32e01dc'
down_revision: Union[str, None] = 'fa4b2a7ee66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
