"""Making entity name nullable

Revision ID: 20ab1a05f587
Revises: 8919304a9c9f
Create Date: 2024-04-29 09:09:31.505836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '20ab1a05f587'
down_revision: Union[str, None] = '8919304a9c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopic_document_link')
    op.alter_column('entity', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('subtopic_document_link',
    sa.Column('subtopic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name='subtopic_document_link_document_id_fkey'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], name='subtopic_document_link_subtopic_id_fkey'),
    sa.PrimaryKeyConstraint('subtopic_id', 'document_id', name='subtopic_document_link_pkey')
    )
    # ### end Alembic commands ###
