"""Adding delete cascade to subtopic relationship

Revision ID: 437a2ef7cd8c
Revises: 07fd4aa16a4b
Create Date: 2024-04-10 16:35:06.565221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '437a2ef7cd8c'
down_revision: Union[str, None] = '07fd4aa16a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
