"""Adding relationship between Document and Entity

Revision ID: 726fcc466cd2
Revises: 28277dd97c87
Create Date: 2024-04-10 12:08:41.665364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '726fcc466cd2'
down_revision: Union[str, None] = '28277dd97c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entity', 'document', ['document_id'], ['id'])
    op.alter_column('subtopic', 'topic_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtopic', 'topic_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'entity', type_='foreignkey')
    # ### end Alembic commands ###
