"""Add embedding to Entity and Id to subtopic

Revision ID: 739f0388d14a
Revises: 437a2ef7cd8c
Create Date: 2024-04-11 12:25:03.125302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '739f0388d14a'
down_revision: Union[str, None] = '437a2ef7cd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    op.add_column('subtopic', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtopic', 'id')
    op.drop_column('entity', 'embedding')
    # ### end Alembic commands ###
