"""Adding metadata fields to Document

Revision ID: 81c78c0a3a60
Revises: 20ab1a05f587
Create Date: 2024-05-20 11:52:27.344362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81c78c0a3a60'
down_revision: Union[str, None] = '20ab1a05f587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('texts2', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('json1', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_entity_link',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'entity_id')
    )
    op.create_table('subtopic_document_link',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], ),
    sa.PrimaryKeyConstraint('subtopic_id', 'document_id')
    )
    op.create_table('subtopic_embedding_link',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_id'], ['embedding.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], ),
    sa.PrimaryKeyConstraint('subtopic_id', 'embedding_id')
    )
    op.drop_table('document_embeddings')
    op.add_column('document', sa.Column('metadata_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('metadata_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('site_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('document', 'authors',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('entity', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('entity', sa.Column('descriptions_bank', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('entity', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_constraint('entity_document_id_fkey', 'entity', type_='foreignkey')
    op.drop_column('entity', 'document_id')
    op.drop_column('entity', 'embedding')
    op.add_column('subtopic', sa.Column('name_update_at', sa.DateTime(), nullable=True))
    op.add_column('subtopic', sa.Column('vector', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    op.add_column('subtopic', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('subtopic', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopic', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True))
    op.drop_column('subtopic', 'update_at')
    op.drop_column('subtopic', 'vector')
    op.drop_column('subtopic', 'name_update_at')
    op.add_column('entity', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('entity_document_id_fkey', 'entity', 'document', ['document_id'], ['id'])
    op.drop_column('entity', 'update_at')
    op.drop_column('entity', 'descriptions_bank')
    op.drop_column('entity', 'version')
    op.alter_column('document', 'authors',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.drop_column('document', 'site_name')
    op.drop_column('document', 'image_url')
    op.drop_column('document', 'locale')
    op.drop_column('document', 'metadata_description')
    op.drop_column('document', 'metadata_keywords')
    op.create_table('document_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embeddings', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='document_embeddings_pkey')
    )
    op.drop_table('subtopic_embedding_link')
    op.drop_table('subtopic_document_link')
    op.drop_table('document_entity_link')
    op.drop_table('testlist')
    op.drop_table('embedding')
    # ### end Alembic commands ###
