"""Adding subtopic document relationship

Revision ID: 8919304a9c9f
Revises: c0eed76b8f45
Create Date: 2024-04-25 16:09:18.504616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8919304a9c9f'
down_revision: Union[str, None] = 'c0eed76b8f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtopic_document_link',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], ),
    sa.PrimaryKeyConstraint('subtopic_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopic_document_link')
    # ### end Alembic commands ###
