"""Adding entity_id to document_embedding

Revision ID: c0eed76b8f45
Revises: 0318c32e01dc
Create Date: 2024-04-17 13:17:22.237886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c0eed76b8f45'
down_revision: Union[str, None] = '0318c32e01dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_embeddings', sa.Column('entity_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_embeddings', 'entity_id')
    # ### end Alembic commands ###
