"""Add subtopic.id

Revision ID: cea88f2b866d
Revises: 739f0388d14a
Create Date: 2024-04-12 11:28:32.299034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'cea88f2b866d'
down_revision: Union[str, None] = '739f0388d14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopic', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('topic', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('topic', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'user_id')
    op.drop_column('topic', 'id')
    op.drop_column('subtopic', 'user_id')
    # ### end Alembic commands ###
