"""Remove topics tables 2

Revision ID: d09840e0c564
Revises: fdb673c5807a
Create Date: 2024-04-12 11:44:12.601061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd09840e0c564'
down_revision: Union[str, None] = 'fdb673c5807a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopic')
    op.drop_table('topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='topic_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('subtopic',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key_words', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_name'], ['topic.name'], name='subtopic_topic_name_fkey'),
    sa.PrimaryKeyConstraint('name', name='subtopic_pkey')
    )
    # ### end Alembic commands ###
