"""Remove topics tables 1

Revision ID: fdb673c5807a
Revises: cea88f2b866d
Create Date: 2024-04-12 11:39:26.159376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'fdb673c5807a'
down_revision: Union[str, None] = 'cea88f2b866d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopic_entity_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtopic_entity_link',
    sa.Column('subtopic_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name='subtopic_entity_link_entity_id_fkey'),
    sa.ForeignKeyConstraint(['subtopic_name'], ['subtopic.name'], name='subtopic_entity_link_subtopic_name_fkey'),
    sa.PrimaryKeyConstraint('subtopic_name', 'entity_id', name='subtopic_entity_link_pkey')
    )
    # ### end Alembic commands ###
