steps:
- id: "Build Docker Image"
  name: 'gcr.io/cloud-builders/docker:latest'
  dir: '.'
  args: ['build', 
          '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/icognition-api-artifact-registry/icognition-api-img',
          '.']

- id: "Push Docker Image To Artifact Registry"
  name: 'gcr.io/cloud-builders/docker:latest'
  args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/${PROJECT_ID}/icognition-api-artifact-registry/icognition-api-img']

- id: "Deploy Cloud Run Service"
  name: 'gcr.io/cloud-builders/gcloud:latest'
  args: [
    'run', 'deploy', 'icognition-api-scv', 
    '--service-account' ,'sa-icognition-api-svc@${PROJECT_ID}.iam.gserviceaccount.com',
    '--allow-unauthenticated',
    '--memory', '512Mi',
    '--platform', 'managed',
    '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/icognition-api-artifact-registry/icognition-api-img',
    '--port', '8080',
    '--timeout', '30',
    '--min-instances', '0',
    '--max-instances', '1',
    '--ingress', 'all',
    '--region', 'us-central1',
    '--set-env-vars', 'DUMMY_USER=777',
    '--set-env-vars', 'INSTANCE_CONNECTION_NAME=strange-tome-412113:us-central1:stg-icog-psql',
    '--set-secrets', 'DATABASE_URL=icog-db-stg-secret:latest',
    '--set-secrets', 'TOGETHER_TOKEN=together-token-secret:latest',
    '--set-secrets', 'DB_NAME=central-db-icog-name:latest',
    '--set-secrets', 'DB_USER=central-db-icog-user:latest',
    '--set-secrets', 'DB_PASSWORD=central-db-icog-password:latest',
    '--add-cloudsql-instances', 'strange-tome-412113:us-central1:stg-icog-psql',
    ]
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
  