import logging, sys
import app.getters as getter
from app.db_connector import get_engine
from app.models import (
    Chat_Message,
    Document,
    Document_Entity_Link,
    Entity,
    Question_Answer,
    Embedding,
    TreeNode,
)
from sqlalchemy.orm import Session
from sqlalchemy import (
    and_,
    select,
    delete,
    func,
    text,
)

logging.basicConfig(
    stream=sys.stdout,
    format="%(asctime)s - %(message)s",
    level=logging.INFO,
    datefmt="%Y-%m-%d %H:%M:%S",
)

engine = get_engine()

### This file contains the logic for deleting records from the database


def delete_chat_message(chat_message_id: int) -> None:
    with Session(engine) as session:
        session.execute(delete(Chat_Message).where(Chat_Message.id == chat_message_id))
        session.commit()


def delete_source_and_associate_records(id: str) -> None:
    """
    Delete a source/bookmark and all associated records from the database.
    This function can handle both source_id and document_id as input.
    
    Args:
        id: Either a source_id or document_id
    """
    try:
        # First determine if the id is a source_id or document_id
        with Session(engine) as session:
            # Try to find a source with this id
            source = session.scalar(select(Source).where(Source.id == id))
            if source:
                # If found, it's a source_id
                source_id = id
                document_id = source.document_id
            else:
                # If not found, assume it's a document_id
                document_id = id
                source = session.scalar(select(Source).where(Source.document_id == document_id))
                source_id = source.id if source else None

        if not source_id and not document_id:
            logging.error(f"No source or document found with id {id}")
            return

        # Delete chat messages first
        with Session(engine) as session:
            session.execute(
                delete(Chat_Message).where(Chat_Message.chat_id == document_id)
            )
            session.commit()
            logging.info(f"Chat messages deleted for document {document_id}")

        # Delete document and its associated records
        if document_id:
            delete_document_and_associate_records(document_id)

        # Delete source if it exists
        if source_id:
            with Session(engine) as session:
                session.execute(delete(Source).where(Source.id == source_id))
                session.commit()
                logging.info(f"Source {source_id} deleted")

    except Exception as e:
        logging.error(f"Error in delete_source_and_associate_records: {str(e)}")
        raise e


def reset_document_for_testing(document_id) -> None:
    """
    This function resets a document for testing purposes.
    It deletes all the records that are generated by LLM that are associated with the document

    Args:
        document_id (int): The id of the document to reset
    """
    logging.info(f"Resetting document {document_id} for testing")
    with Session(engine) as session:

        delete_document_embedding_and_associate_records(document_id)

        doc = session.scalar(select(Document).where(Document.id == document_id))
        doc.ai_is_about = None
        doc.ai_bullet_points = None
        doc.ai_citations = None

        session.commit()

        delete_doc_ent_links = session.scalars(
            select(Document_Entity_Link).where(
                Document_Entity_Link.document_id == document_id
            )
        ).all()
        for delink in delete_doc_ent_links:
            session.delete(delink)

        session.commit()

        logging.info(f"Document {document_id} reset for testing")


def delete_document_embedding_and_associate_records(document_id) -> None:

    with Session(engine) as session:
        del_emb_link = text(
            """
                    DELETE 
                        FROM subtopic_embedding_link sel 
                        WHERE sel.embedding_id IN (SELECT DISTINCT e.id FROM embedding e WHERE e.source_id = :id and e.source_type = 'document')"""
        )
        result_emb_link = session.execute(del_emb_link, {"id": document_id})

        del_emb = text(
            """DELETE FROM embedding e WHERE e.source_id = :id and e.source_type = 'document'"""
        )
        result_emb = session.execute(del_emb, {"id": document_id})


def delete_question_and_answer_associated_with_document(document_id) -> None:

    with Session(engine) as session:
        session.execute(
            delete(Question_Answer).where(Question_Answer.document_id == document_id)
        )
        session.commit()


def delete_entities_associated_with_document(document_id: str) -> None:

    with Session(engine) as session:
        entities_ids = (
            session.scalars(
                select(Document_Entity_Link.entity_id).where(
                    Document_Entity_Link.document_id == document_id
                )
            )
            .unique()
            .all()
        )
        for id in entities_ids:
            session.execute(
                delete(Document_Entity_Link).where(
                    Document_Entity_Link.entity_id == id,
                    Document_Entity_Link.document_id == document_id,
                )
            )
            session.execute(delete(Embedding).where(Embedding.source_id == id))
            session.commit()


def delete_orphaned_entities() -> None:
    with Session(engine) as session:
        delete_entities = session.scalars(
            select(Entity).where(
                ~Entity.id.in_(select(Document_Entity_Link.entity_id).distinct())
            )
        ).all()
        for entity in delete_entities:
            session.delete(entity)
        session.commit()
        logging.info(f"Orphaned entities deleted")


def delete_document_associate_records(document_id: str) -> None:
    """
    This function deletes a document and all associated records from the database.
    This function was create for testing purposes.
    """
    logging.info(f"Deleting document {document_id} and associated records")
    with Session(engine) as session:
        

        session.flush()
        delete_doc_ent_links = session.scalars(
            select(Document_Entity_Link).where(
                Document_Entity_Link.document_id == document_id
            )
        ).all()
        for delink in delete_doc_ent_links:
            session.delete(delink)

        delete_question_and_answer_associated_with_document(document_id)

        delete_doc_embs = session.scalars(
            select(Embedding).where(Embedding.source_id == document_id)
        ).all()
        emb_ids = []
        for emb in delete_doc_embs:
            emb_ids.append(emb.id)
            session.delete(emb)

        session.flush()

        session.commit()
        logging.info(f"Associated record of document {document_id} deleted")


def delete_document_and_associate_records(document_id: str) -> None:
    """
    This function deletes a document and all associated records from the database.
    This function was create for testing purposes.
    """
    logging.info(f"Deleting document {document_id} and associated records")
    delete_document_associate_records(document_id)
    with Session(engine) as session:

        session.execute(delete(Document).where(Document.id == document_id))
        session.execute(delete(Source).where(Source.document_id == document_id))

        session.commit()
        logging.info(f"Document {document_id} and associated records deleted")


def delete_all_of_users_records(user_id: str) -> None:
    """Delete all of the records for a user. This function was create for testing

    Args:
        user_id int
    """
    bookmarks = getter.get_sources_by_user_id(user_id)
    for bookmark in bookmarks:
        delete_source_and_associate_records(bookmark.id)
