"""remove_firebase_uid_from_users

Revision ID: 01bed05e2b42
Revises: 738216f2933b
Create Date: 2025-09-21 12:45:45.318530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01bed05e2b42'
down_revision: Union[str, Sequence[str], None] = '738216f2933b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop foreign key constraints that depend on entity_id columns (if they exist)
    op.execute("ALTER TABLE document_entity_link DROP CONSTRAINT IF EXISTS document_entity_link_entity_id_fkey")
    op.execute("ALTER TABLE entity_documents DROP CONSTRAINT IF EXISTS entity_documents_entity_id_fkey")
    op.execute("ALTER TABLE entity_user_link DROP CONSTRAINT IF EXISTS entity_user_link_entity_id_fkey")
    
    # Now change entity_id columns to VARCHAR
    op.alter_column('document_entity_link', 'entity_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('entity_documents', 'entity_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('entity_user_link', 'entity_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    
    # Also change entities.id to VARCHAR to match
    op.execute("ALTER TABLE entities ALTER COLUMN id TYPE VARCHAR USING id::varchar")
    
    # Recreate foreign key constraints
    op.create_foreign_key('document_entity_link_entity_id_fkey', 'document_entity_link', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key('entity_documents_entity_id_fkey', 'entity_documents', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key('entity_user_link_entity_id_fkey', 'entity_user_link', 'entities', ['entity_id'], ['id'])
    
    # Remove firebase_uid from users table
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.alter_column('entity_user_link', 'entity_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'entity_documents', type_='foreignkey')
    op.alter_column('entity_documents', 'entity_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('document_entity_link', 'entity_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
