"""change_user_id_to_string_for_firebase_integration

Revision ID: 04798c04400a
Revises: 4679c3f66339
Create Date: 2025-09-21 11:57:39.354804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04798c04400a'
down_revision: Union[str, Sequence[str], None] = '4679c3f66339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop ALL foreign key constraints that depend on user tables
    op.drop_constraint(op.f('entity_user_link_user_id_fkey'), 'entity_user_link', type_='foreignkey')
    op.drop_constraint(op.f('bookmarks_user_id_fkey'), 'bookmarks', type_='foreignkey')
    op.drop_constraint(op.f('document_user_id_fkey'), 'document', type_='foreignkey')
    op.drop_constraint(op.f('entities_user_id_fkey'), 'entities', type_='foreignkey')
    
    # Now we can safely drop the 'user' table
    op.drop_table('user')
    
    # Change users.id from integer to string FIRST
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    
    # Now change all user_id columns from integer to string
    op.alter_column('bookmarks', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('document', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('entities', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    
    # Recreate all foreign key constraints pointing to 'users' table
    op.create_foreign_key(None, 'entity_user_link', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bookmarks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'document', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'entities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'entity_user_link', type_='foreignkey')
    op.create_foreign_key(op.f('entity_user_link_user_id_fkey'), 'entity_user_link', 'user', ['user_id'], ['id'])
    op.alter_column('entities', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('document', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('bookmarks', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    # ### end Alembic commands ###
