"""add_entity_relationships

Revision ID: 0e3c95d9a1e4
Revises: 9699d5d5c384
Create Date: 2026-03-02 13:24:33.442611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e3c95d9a1e4'
down_revision: Union[str, Sequence[str], None] = '9699d5d5c384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_rel_unique', 'entity_relationships', ['from_entity_id', 'to_entity_id', 'relationship_type', 'source_document_id'], unique=True)
    op.create_index(op.f('ix_entity_relationships_from_entity_id'), 'entity_relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_relationship_type'), 'entity_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_document_id'), 'entity_relationships', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_to_entity_id'), 'entity_relationships', ['to_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_relationships_to_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_document_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_relationship_type'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_from_entity_id'), table_name='entity_relationships')
    op.drop_index('ix_entity_rel_unique', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    # ### end Alembic commands ###
