"""add_document_id_to_bookmarks

Revision ID: 1c14aaf185a3
Revises: ce461df87680
Create Date: 2025-09-20 10:12:28.024841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c14aaf185a3'
down_revision: Union[str, Sequence[str], None] = 'ce461df87680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_bookmarks_document_id'), 'bookmarks', ['document_id'], unique=False)
    op.create_foreign_key(None, 'bookmarks', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.drop_index(op.f('ix_bookmarks_document_id'), table_name='bookmarks')
    op.drop_column('bookmarks', 'document_id')
    # ### end Alembic commands ###
