"""add_content_source_to_documents

Revision ID: 32c9bd0041ac
Revises: c867be2c6192
Create Date: 2025-09-09 21:53:36.829251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c9bd0041ac'
down_revision: Union[str, Sequence[str], None] = 'c867be2c6192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_source', sa.String(length=20), nullable=False, server_default='url'))
    op.alter_column('documents', 'url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    # Remove the test table changes as they're not needed for our feature
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    op.drop_column('documents', 'content_source')
    # ### end Alembic commands ###
