"""fix_entity_foreign_key_references

Revision ID: 738216f2933b
Revises: 9af99eaa8e70
Create Date: 2025-09-21 12:33:26.899634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '738216f2933b'
down_revision: Union[str, Sequence[str], None] = '9af99eaa8e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop all foreign key constraints that depend on the 'entity' table
    op.drop_constraint(op.f('document_entity_link_entity_id_fkey'), 'document_entity_link', type_='foreignkey')
    op.drop_constraint(op.f('entity_user_link_entity_id_fkey'), 'entity_user_link', type_='foreignkey')
    
    # Also drop any remaining constraints on entity_documents table
    op.execute("ALTER TABLE entity_documents DROP CONSTRAINT IF EXISTS entity_documents_entity_id_fkey")
    
    # Now we can safely drop the 'entity' table
    op.drop_table('entity')
    
    # Change entities.id from VARCHAR to Integer
    # Use raw SQL with USING clause to handle the type conversion
    op.execute("ALTER TABLE entities ALTER COLUMN id TYPE INTEGER USING id::integer")
    
    # Also change entity_id columns in related tables to INTEGER
    op.execute("ALTER TABLE entity_documents ALTER COLUMN entity_id TYPE INTEGER USING entity_id::integer")
    op.execute("ALTER TABLE entity_user_link ALTER COLUMN entity_id TYPE INTEGER USING entity_id::integer")
    op.execute("ALTER TABLE document_entity_link ALTER COLUMN entity_id TYPE INTEGER USING entity_id::integer")
    
    # Recreate foreign key constraints pointing to 'entities' table
    op.create_foreign_key(None, 'document_entity_link', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key(None, 'entity_user_link', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity_user_link', type_='foreignkey')
    op.create_foreign_key(op.f('entity_user_link_entity_id_fkey'), 'entity_user_link', 'entity', ['entity_id'], ['id'])
    op.alter_column('entities', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('entities_id_seq'::regclass)"))
    op.drop_constraint(None, 'document_entity_link', type_='foreignkey')
    op.create_foreign_key(op.f('document_entity_link_entity_id_fkey'), 'document_entity_link', 'entity', ['entity_id'], ['id'])
    op.create_table('entity',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('normalized_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verbatim_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wikidata_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wikidata_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wikidata_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wikidata_pageviews', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wikidata_instance_of', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description_vector', pgvector.sqlalchemy.vector.VECTOR(dim=3072), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_pkey'))
    )
    # ### end Alembic commands ###
