"""Fix User.id to str for Firebase UIDs and update foreign keys

Revision ID: 9596666adb53
Revises: 1d24eec09a9f
Create Date: 2025-10-21 20:52:51.976949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9596666adb53'
down_revision: Union[str, Sequence[str], None] = '1d24eec09a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraints first
    op.drop_constraint('bookmarks_user_id_fkey', 'bookmarks', type_='foreignkey')
    op.drop_constraint('document_user_id_fkey', 'document', type_='foreignkey')
    op.drop_constraint('entities_user_id_fkey', 'entities', type_='foreignkey')
    op.drop_constraint('entity_user_link_user_id_fkey', 'entity_user_link', type_='foreignkey')
    
    # Drop the sequence for users.id since we're changing to string
    op.execute("DROP SEQUENCE IF EXISTS users_id_seq CASCADE")
    
    # Change user_id columns to string
    op.alter_column('bookmarks', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('document', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('entities', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('entity_user_link', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    
    # Change users.id to string (no sequence)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    
    # Recreate foreign key constraints
    op.create_foreign_key('bookmarks_user_id_fkey', 'bookmarks', 'users', ['user_id'], ['id'])
    op.create_foreign_key('document_user_id_fkey', 'document', 'users', ['user_id'], ['id'])
    op.create_foreign_key('entities_user_id_fkey', 'entities', 'users', ['user_id'], ['id'])
    op.create_foreign_key('entity_user_link_user_id_fkey', 'entity_user_link', 'users', ['user_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraints first
    op.drop_constraint('bookmarks_user_id_fkey', 'bookmarks', type_='foreignkey')
    op.drop_constraint('document_user_id_fkey', 'document', type_='foreignkey')
    op.drop_constraint('entities_user_id_fkey', 'entities', type_='foreignkey')
    op.drop_constraint('entity_user_link_user_id_fkey', 'entity_user_link', type_='foreignkey')
    
    # Change users.id back to integer with sequence
    op.alter_column('users', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    
    # Create sequence for users.id
    op.execute("CREATE SEQUENCE users_id_seq")
    op.execute("ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq')")
    op.execute("ALTER SEQUENCE users_id_seq OWNED BY users.id")
    
    # Change user_id columns back to integer
    op.alter_column('entity_user_link', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('entities', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('document', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('bookmarks', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    
    # Recreate foreign key constraints
    op.create_foreign_key('bookmarks_user_id_fkey', 'bookmarks', 'users', ['user_id'], ['id'])
    op.create_foreign_key('document_user_id_fkey', 'document', 'users', ['user_id'], ['id'])
    op.create_foreign_key('entities_user_id_fkey', 'entities', 'users', ['user_id'], ['id'])
    op.create_foreign_key('entity_user_link_user_id_fkey', 'entity_user_link', 'users', ['user_id'], ['id'])
    
    # ### end Alembic commands ###
