"""Change ai_bullet_points to ai_markdown_content

Revision ID: 9699d5d5c384
Revises: d61403a96d4d
Create Date: 2026-02-25 08:01:12.158120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9699d5d5c384'
down_revision: Union[str, Sequence[str], None] = 'd61403a96d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('ai_markdown_content', sa.Text(), nullable=True))
    op.drop_column('document', 'ai_bullet_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('ai_bullet_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('document', 'ai_markdown_content')
    # ### end Alembic commands ###
