"""fix_entity_document_entity_id_type

Revision ID: 9af99eaa8e70
Revises: 04798c04400a
Create Date: 2025-09-21 12:10:42.619837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9af99eaa8e70'
down_revision: Union[str, Sequence[str], None] = '04798c04400a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the foreign key constraint
    op.drop_constraint('entity_documents_entity_id_fkey', 'entity_documents', type_='foreignkey')
    
    # Change entities.id from integer to string FIRST
    op.alter_column('entities', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    
    # Now change entity_documents.entity_id from integer to string
    op.alter_column('entity_documents', 'entity_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    
    # Recreate the foreign key constraint
    op.create_foreign_key('entity_documents_entity_id_fkey', 'entity_documents', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint
    op.drop_constraint('entity_documents_entity_id_fkey', 'entity_documents', type_='foreignkey')
    
    # Change entity_documents.entity_id back to integer
    op.alter_column('entity_documents', 'entity_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    
    # Change entities.id back to integer
    op.alter_column('entities', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    
    # Recreate the foreign key constraint
    op.create_foreign_key('entity_documents_entity_id_fkey', 'entity_documents', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###
