"""remove_source_and_update_bookmark_uuid

Revision ID: ce461df87680
Revises: 06103d45605f
Create Date: 2025-09-19 17:39:47.513565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce461df87680'
down_revision: Union[str, Sequence[str], None] = '06103d45605f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Enable UUID extension
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    
    # Step 2: Drop source table
    op.drop_table('source')
    
    # Step 3: Convert bookmarks.id from INTEGER to UUID
    # First, add a new UUID column
    op.add_column('bookmarks', sa.Column('new_id', sa.UUID(), nullable=True))
    
    # Generate UUIDs for existing records
    op.execute("UPDATE bookmarks SET new_id = uuid_generate_v4() WHERE new_id IS NULL")
    
    # Make the new column NOT NULL
    op.alter_column('bookmarks', 'new_id', nullable=False)
    
    # Drop the old primary key constraint
    op.drop_constraint('bookmarks_pkey', 'bookmarks', type_='primary')
    
    # Drop the old id column
    op.drop_column('bookmarks', 'id')
    
    # Rename new_id to id
    op.alter_column('bookmarks', 'new_id', new_column_name='id')
    
    # Create new primary key constraint
    op.create_primary_key('bookmarks_pkey', 'bookmarks', ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('source',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cloned_documents', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('html_root_element', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('source_pkey'))
    )
    # ### end Alembic commands ###
