name: CI/CD Pipeline for FastAPI Application

on:
  push:
    branches:
      - light_tests  # light_tests is the name of the branch where you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode GCP Service Account Key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > "$HOME/gcp-service-account-key.json"
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} # Use the name of your secret
        shell: bash

      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-service-account-key.json" >> $GITHUB_ENV

      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: strange-tome-412113  # Remove the backslash at the end of this line
          export_default_credentials: true

      - name: Configure gcloud CLI
        run: gcloud config set project strange-tome-412113

      # Assuming you've already created an App Engine application, you may not need this step.
      # Uncomment and use it if you're setting up the App Engine app for the first time.
      # - name: Create App Engine Application
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   run: gcloud app create --project=${{ env.GCLOUD_PROJECT }} --region=us-central
      #   env:
      #     GCLOUD_PROJECT: strange-tome-412113

      - name: Deploy to Google App Engine
        run: gcloud app deploy app.yml --quiet
        # working-directory: .

      
      - name: Set up GCP SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          service_account_key: ${{ secrets.GCP_SQL_DEV_KEY }}
          instances: strange-tome-412113:us-east1:app-engine-psql
      
      - name: Run Alembic migrations
        run: alembic upgrade head
        env:
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}